import enum


class Token(enum.Enum):
    FUNCTION = "function"
    ARGUMENT = "argument"
    CALL = "call"
    RETURN = "return"
    PLUS = "plus"
    MINUS = "minus"
    TIMES = "times"
    DOT = "dot"
    DIVIDE = "divide"
    THEN = "then"
    GREATER_THAN = "greater_than"
    LESS_THAN = "less_than"
    GREATER_THAN_OR_EQUAL_TO = "greater_than_or_equal_to"
    LESS_THAN_OR_EQUAL_TO = "less_than_or_equal_to"
    IF = "if"
    ELSE = "else"
    SET = "set"
    EQUALS = "equals"
    AND = "and"
    OR = "or"
    APPEND = "append"
    PREPEND = "prepend"
    FOR = "for"